Module 4-3
htmlacademy-nodejs/84251-typoteka-3 pull request #13
Opened 2021-05-24 20:37 UTC by sergejc

2021-05-25 18:25 UTC, copperkraft requested changes

2021-05-25 18:25 UTC, copperkraft commented on src/express/routes/index.js
> +    let data = {};
Во первых, я бы не рекомендовал использовать `let` чтобы создать пустую переменную и заполнить ее данными позже. В идеальном случае переменную можно не использовать или использовать `const`. 

Конкретно тут я бы сразу обработал случай с пустым `query.search` и вышел из функции. Затем можно без `else` работать с данными напрямую.

Кроме того, можно будет воспользоваться деструктуризацией и достать `data` без дополнительной переменной `response`

2021-05-25 18:25 UTC, copperkraft commented on src/express/routes/index.js
> +router.get(`/search`, async (req, res) => {
Лично на мой вкус, я бы отделял каждый `router.get(.....)` пустой строкой, так как по сути в них хранится разнородная логика и нет той повторяемости, которая была, когда возвращали просто адреса запросов. (`pages/login`)

2021-05-25 18:25 UTC, copperkraft commented on src/express/routes/index.js
> +        const response = await axios.get(`http://localhost:3000/api/search`, { params: { query: search } });
Я бы сохранил `http://localhost:3000/api` в константу `API_URL` и в `.get()` было бы что-то вроде ` '${API_URL}/search'`

2021-05-25 18:25 UTC, copperkraft commented on src/express/routes/index.js
> +    if(title, announce, fullText) {
Не уверен, что ты хочешь тут сделать, но если проверить, что все три переменные не `undefined`, то тебе нужен был `&&` оператор (AND). Если ты просто перечисляешь выражения в JS через запятую, то в итоге используется только последнее.

2021-05-25 18:25 UTC, copperkraft commented on src/express/templates/pages/new-post.pug
> +                form(action='/articles/add', method='POST')
Не совсем понимаю, почему метод `'POST'`, а не `'post'`, но я может что-то просто пропустил.

2021-05-26 06:52 UTC, sergejc commented on src/express/routes/index.js
> +    if(title, announce, fullText) {
Банальная опечатка или cope/paste )

2021-05-27 05:44 UTC, merged